import type { Metadata } from "next";
//import { Inter } from "next/font/google";
import "./globals.css";
import { Lato } from "next/font/google";
import { Header } from "@/components/Header";

const lato = Lato({ subsets: ["latin"], weight:['400','700'] });

export const metadata: Metadata = {
  title: "Estudos CodeBoost",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={lato.className}>
      <Header />
      {children}</body>
    </html>
  );
}
